tasks:
  - name: Setup ROS Workspace
    init: |
      # Clone prerequisite repositories
      git clone https://git.cardiff.ac.uk/comp_robot/slam_examples.git src/slam_examples
      git clone https://git.cardiff.ac.uk/comp_robot/grid_planners_demo.git src/grid_planners_demo
      git clone https://git.cardiff.ac.uk/comp_robot/sampling_planners_demo.git src/sampling_planners_demo
      git clone https://git.cardiff.ac.uk/comp_robot/path_follower.git src/path_follower
      # Build the workspace
      source /opt/ros/humble/setup.bash
      colcon build --symlink-install
    command: |
      echo "Workspace is ready. Source it with: source install/setup.bash"
      source install/setup.bash

vscode:
  extensions:
    - ms-python.python
    - ms-vscode.cpptools
    - ms-iot.vscode-ros