waypoints:
  - name: "center_of_large_room"
    pose:
      position:
        x: 0.5
        y: 0.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 0.0
        w: 1.0
  - name: "top_right_corner"
    pose:
      position:
        x: 1.5
        y: 1.5
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: -0.707
        w: 0.707
  - name: "entrance_of_small_room"
    pose:
      position:
        x: -1.5
        y: 1.0
        z: 0.0
      orientation:
        x: 0.0
        y: 0.0
        z: 1.0
        w: 0.0